sudo: false
language: ruby
rvm:
  - 2.4.0
before_install:
- gem install bundler -v 1.14.6
- git clone --depth 1 https://github.com/antirez/redis.git
- cd redis
- make
- cd ..
- git clone --depth 1 https://github.com/RedisLabsModules/RediSearch.git
- cd RediSearch/src
- make all
- cd ..
