sudo: required
dist: trusty
language: ruby
rvm:
  - 2.4.1
before_install:
- gem install bundler -v 1.14.6
- git clone --depth 10 https://github.com/antirez/redis.git
- cd redis
- git fetch && git fetch --tags
- git checkout 4.0.6
- make
- cd ..
- git clone --depth 1 https://github.com/RedisLabsModules/RediSearch.git
- cd RediSearch
- git fetch && git fetch --tags
- git checkout v1.2.0
- make all
- cd ..

